### ISSUE TITLE
Retest

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-test#10]
Brain storming idea:

It would be nice if there was a retest option.  I.e. if the output directory exists, only run the tests that failed (or weren't run because testing was aborted early) the last time.  This would make it easier to tell if one has fixed what was previously broken (though a full run would still be necessary to make sure that the fix didn't break anything else).

**Comment by henryso** [comment]
Not a bad idea.  I'll figure it out.

**Comment by henryso** [comment]
Use the `-r` switch to re-run the failed tests.
