### ISSUE TITLE
Add nabc tests

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio-test#111]
It would be important to have a few nabc tests, testing different `nabc-lines` value

**Comment by rpspringuel** [comment]
I'll admit I haven't been paying much attention to the nabc development, but I thought that `1` was the only value for `nabc-lines` currently supported.

**Comment by jakubjelinek** [comment]
Yes, that is true.  Supporting other values will make sense when we a) support some other neume kind (e.g. Laon) and b) support emitting one nabc line above notes and one below notes, or two above etc.

**Comment by henryso** [comment]
What's the right way to test `nabc-lines` other than `1`?  Can you give me examples, or does that not make sense right now?

**Comment by eroux** [comment]
That doesn't make much sense right now
