### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-test#13]
It would be nice if there was some sort of progress indicator which showed how far along in the tests the script was.  Personally I'd be satisfied if the progress was simply percentage of the tests which have been completed, even though some tests take longer than others.  The one issue would be that the script would have to calculate the number of tests it was going to run at the very beginning before running any tests in order to get the denominator needed for a percentage.  Would that be something difficult?

Once how to calculate the progress is figured out, there are some ideas for how progress bars might be implemented [here](http://stackoverflow.com/questions/238073/how-to-add-a-progress-bar-to-a-shell-script).

**Comment by henryso** [comment]
The tests essentially run in separate processes.  They are launched using xargs, which returns when all the threads have completed.  Therefore, doing this is not so straightforward, but I'll see if I can figure something out.  Would it be good enough to simply display something like `Ran X of Y tests`?

**Comment by rpspringuel** [comment]
That would certainly be an acceptable alternative if that's all you can get.

**Comment by henryso** [comment]
Done.  Use the `-P` flag or set `PROGRESS_BAR=true` in `gregorio-test.rc`.
