### ISSUE TITLE
use lua cache manager

### ISSUE THREAD

**Issue by eroux** [gregorio-project/gregorio-test#155]
Using https://github.com/kalrish/luatex-lua-module-cache-manager would certainly speed up the testing process in a signficant way. I propose to remove the cache at the beginning of each call to `./gregorio-test`, so that it's always up to date.

**Comment by henryso** [comment]
It's not working, but I'm not sure why.  I can see (from the log) the script load and try to read the cache from a non-existent file, but it never caches any modules and then (of course) finds no need to update the cache file with anything.

**Comment by henryso** [comment]
I got it working, but enabling the cache causes our tests to fail if the same cache is used for all the tests.  Using a different cache for each test defeats the purpose of caching in the first place.  Thoughts?

**Comment by henryso** [comment]
A bug in luatex is preventing the proper use of the cache manager.  We should wait until the fix has been released more widely.  See kalrish/luatex-lua-module-cache-manager#2.

**Comment by eroux** [comment]
good job!

**Comment by henryso** [comment]
Does anyone know which version of LuaTeX will be going into TeX Live 2016?  If it's newer than 0.89.1, then I think I can enable this once TeX Live 2016 is released.

**Comment by eroux** [comment]
I believe it's 0.95

**Comment by rpspringuel** [comment]
I can confirm that it is 0.95

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by henryso** [comment]
Using the cache manager had a negative effect on run times.
