### ISSUE TITLE
Diff color palette

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-test#18]
Is it possible to change the color palette for the diff images?  The current color palette (red: old; darker red: new; gray: both) makes it some what difficult to identify the direction of the changes at a glance.  Personally I'd much prefer if the new stuff was highlighted in green or blue to make for a more visual distinction with the old stuff.

**Comment by henryso** [comment]
The tests use imagemagick compare, and you can only select one color for the diffs, for which it uses light and dark versions to mark the differences.  If you (or anyone, for that matter) can figure out a way to change this behavior, I'm all ears.

**Comment by henryso** [comment]
I might have a lead from http://www.imagemagick.org/discourse-server/viewtopic.php?t=26105.  Let me see if I can figure out how to make it work.

**Comment by rpspringuel** [comment]
Very good, but the color scheme is backwards from what I wanted (old in red, new in blue).  To me it makes more sense that way because the old pixels have been "deleted" while the new ones have been "added" and Track Changes type things usually mark deletions in red and additions in blue.

Changing that is fairly straight forward, do you mind if I do that?

**Comment by henryso** [comment]
Sure.  It all depends on perception.  I saw blue as good (expected) and red as bad (not as expected).

**Comment by rpspringuel** [comment]
I hadn't thought of it that way.

Would it make more sense then to allow the user to customize those colors via variables set in the rc file?  That's a bit more complicated, but I think still doable.

**Comment by henryso** [comment]
No, go ahead and do what you want with the colors.  It really doesn't matter to me all that much.  I was just explaining why I colored them that way.

**Comment by rpspringuel** [comment]
Done.
