### ISSUE TITLE
The output of fix-43 doesn't match expectation in release-4.1

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio-test#184]
Using the current release-4.1 in gregorio and gregorio-test, the output of fix-43 looks like this:

![image](https://cloud.githubusercontent.com/assets/421318/13516820/c4d8f4e6-e18b-11e5-8e66-70e755d6dc74.png)

... which doesn't match the expectation.  Should I accept this result?

**Comment by rpspringuel** [comment]
I've been leaving that test un accept because there's a bug in the new result. 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by henryso** [comment]
Thanks.
