### ISSUE TITLE
Custos-after-bar butting up against following note

### ISSUE THREAD

**Issue by henryso** [gregorio-project/gregorio-test#188]
In tex-output/illumination/illumination.tex and tex-output/hyphenation/hyphenation.tex (which use the same gabc), the output looks like this:

![image](https://cloud.githubusercontent.com/assets/421318/13527779/86b9b020-e1df-11e5-927d-00f2275f4b66.png)

This is the accepted result.  Is that correct?

**Comment by eroux** [comment]
Thanks, I saw that but was distracted by something else and forgot to report it. Looking back at it, I think I know where it may come from... I'll take a look later tonight or tomorrow
