### ISSUE TITLE
Test Slow down

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-test#224]
Has any one else expereinced a dramatic slow down in the tests recently?  My computer has always been somewhat slow at running the whole suite (it's what I get for saving money and buying a 5 year old model), but recently things have been taking much longer.  I'm trying to figure out if it is something particular to my computer or something related to the tests themselves.

**Comment by henryso** [comment]
I increased the resolution of the PDF compare.  That definitely slowed it down on my computer.  I can switch it back, but we'll lose some accuracy in the comparison.

**Comment by rpspringuel** [comment]
Of course, that would slow things down.

Rather than just decreasing the resolution, could it be converted into a settable option?  After all, you increased the resolution in order to see changes that weren't being caught at the lower resolution, and so there are clearly occasions where the higher resolution is necessary.  However, I don't think it's needed for most changes so having a lower default would be more efficient, but having the option to increase the resolution when needed is still important.

**Comment by henryso** [comment]
Sounds like a good idea.  I will try to implement this tonight.

**Comment by henryso** [comment]
Set PDF_DENSITY to something smaller than 300 (it was 150 prior to the switch to 300) in your `gregorio-test.rc` file or from the command-line environment, depending on your desired permanency.
