### ISSUE TITLE
Converted pages merged together

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-test#278]
I just noticed that when a multi-page document in the test repository is converted to png, all the pages get merged into one page.  I don't recall this happening before.  Are other people experiencing this?  Has something changed that I'm just not recalling?

**Comment by henryso** [comment]
That doesn't happen for me.  What version of imagemagick is on your computer?

**Comment by henryso** [comment]
I think I figured it out.  Depending on the version of imagemagick/graphicsmagick, the `-average` flag might cause the images to be merged.  #279 should fix that.

**Comment by rpspringuel** [comment]
I'm running ImageMagick 6.9.6-2.

I'll check out the fix just as soon as I finish resetting MacPorts (finally got around to installing El Capitan since this computer won't take Sierra and that necessitates rebuilding all my ports).
