### ISSUE TITLE
Strange errors

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-test#3]
I'm getting some strange errors when running the tests against the latest develop.

Every test which produces pdf output is failing (with a small handful of exceptions), with the testing routine being unable to typeset the test document.  When I check the specific errors of a handful of the tests at random, they all appear to have failed with the following error:
```
!LuaTeX error: cannot find OpenType font file for reading ()
 ==> Fatal error occurred, no output PDF file produced!
```
In some cases, the log file indicates that what was happening just before that error was an attempt to load a font, but in other cases that doesn't appear to be the case.  This only happens when working with the tests.  A spot check of some of my personal projects reveals that they compile just fine (though with the expected deprecation errors since they have not been updated).

**Comment by henryso** [comment]
Please supply the complete command you are using to run the tests.  Also, since I cannot reproduce this problem, can you send me some of the log files as well as some of the corresponding cmdout files?

**Comment by rpspringuel** [comment]
I'm simply invoking the test script: `./gregorio-test.sh`

Files should be on the way.  Let me know if you don't get them.

**Comment by henryso** [comment]
Do the Alegreya fonts exists in the gregorio-test/fonts directory?  Is AlegreyaSC-Bold.otf there?

**Comment by rpspringuel** [comment]
All the Alegreya*.otf fonts are in the fonts directory.

**Comment by henryso** [comment]
I can't explain it and I can't reproduce it.  I don't know what it's looking for (it appears to be looking for an empty string ().  Maybe I'll have an epiphany, but I can't tell what's wrong here.

**Comment by rpspringuel** [comment]
I don't have time today, but I'll try a clean clone tomorrow and see if that makes a difference.

**Comment by henryso** [comment]
If that doesn't help, maybe you can go backwards in history as 'gregorio-test.sh', 'harness.sh', and/or 'gabc-output.tex' change and see if some earlier version does happen to work.  That'll make it easier to figure out which change broke it.

**Comment by henryso** [comment]
@rpspringuel Please see my comment in https://github.com/gregorio-project/gregorio/pull/531#issuecomment-118125098

**Comment by rpspringuel** [comment]
I'm installing the branch I'm trying to test and then testing against the installed version, not against a temp version, so I don't have a `var` directory to delete.

**Comment by henryso** [comment]
Try clearing your TEXMFVAR directory (`kpsewhich --var-value TEXMFVAR`).  This is the equivalent of the gregorio-test `var/texmf-var` directory.

**Comment by rpspringuel** [comment]
That appears to have fixed the problem.
