### ISSUE TITLE
Syllable Rewriting test not clear

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-test#308]
I was just looking over the syllable rewriting test and noticed that there don't appear to be any ligatures created by the syllable rewriting in the score used in the test.  I think that test would be better if the syllable rewriting actually resulted in the creation of a ligature that wouldn't otherwise be there (since that's the main point of the feature).

**Comment by henryso** [comment]
I'm open to ideas of how to do this.  Obviously what I came up with is not sufficient.

**Comment by rpspringuel** [comment]
I think the test can be totally artificial in this respect and not worry about using actual music, or even words for that matter.  What is needed is a list of the ligatures in the test font, and then a sequence of syllables in which the letters that make up those ligatures are split between two syllables whose notes sequences are small enough that they syllables are set without a hyphen between them.  In this way the one can clearly see the ligatures when the syllable rewriting is active and see the distinct letters when it is not.

**Comment by henryso** [comment]
Ok, maybe it'll be better to find a font with extensive ligatures (sort of like the Zapfino font, but freely redistributable).  I'll see what I can find.

**Comment by rpspringuel** [comment]
Hmmm... Based on my testing Alegreya may have some ligatures defined in the font, but I cannot seem to turn them on so they happen automatically (as opposed to just when the Unicode character is encountered).  Check 67df5c85cf3428ec8eb5674a799959bcc12b5c90 for a modified form of the test which prints out a table designed to test the ligatures in normal text.  You'll notice that the second two columns are identical where as if the ligatures were turned on properly it would be the first and last column which are the same.

Unless I've done something wrong in trying to turn on all the ligatures, we need to either modify the font to make the ligatures work, or use a different font where the are already functional.

**Comment by henryso** [comment]
How about this, using the SIL OFL-licensed font Gatometrix:

![image](https://user-images.githubusercontent.com/421318/36357175-34125ebc-14c8-11e8-9ca2-8e70d1376bec.png)

Gatometrix has a lot of weird ligatures, but the one in question here is the "re" ligature.

If that's sufficient, I'll commit it.

**Comment by rpspringuel** [comment]
That looks good.  

An explanation at the top of the file to remind us down the road of what to look for would probably help too.

**Comment by henryso** [comment]
OK, I'll add that as well
