### ISSUE TITLE
Can't find executable in TL2017 pretest

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-test#313]
I'm trying to test the TL2017 pretest to make sure our package is working as expected, and I've discovered that `gregorio-test.sh` can't find the `gregorio` executable in the pretest.  I think it's because it's looking for (and not finding) the version suffix.  I'm not sure, but a possible fix might be to bring the hyphen which separates `gregorio` from the suffix into the `$gregorio_version` variable.  In this fashion when the test script fails to find the version suffix, it will look for an unsuffixed executable.

**Comment by henryso** [comment]
The problem is more complex than that.  The script probes gregoriotex.lua for `local gregorio_exe`, which no longer exists in the new code.  I'll try to work on this next weekend.

**Comment by eroux** [comment]
did you report the bug on the luatex or texlive mailing list?

**Comment by rpspringuel** [comment]
I'm working on the bug report. 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ

**Comment by henryso** [comment]
@rpspringuel Were you able to pull together an MWE?

**Comment by rpspringuel** [comment]
That's what I'm working on. 

✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝✝
Br. Samuel, OSB
(R. Padraic Springuel)
PAX ☧ ΧΡΙΣΤΟΣ
