### ISSUE TITLE
Run Specific tests

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-test#6]
Is it possible to specify a specific test or group of tests for the script to run, ignoring the others?  If not, this might be a good thing to add as it would help speed up the process of testing bug fixes as one could concentrate only on the the tests that display the bug (or some representative of them) and only rerun the whole suite when a potential fix has been identified.

**Comment by henryso** [comment]
Yes, you can specify the tests you want to run on the command line:

For example:
```
./gregorio-test.sh tex-output/SalveReginaOP/SalveReginaOP.tex
```
or
```
./gregorio-test.sh tex-output/SalveReginaOP/SalveReginaOP.tex plain-tex/PopulusSion/PopulusSion.tex
```
or
```
./gregorio-test.sh tests/gabc-dump/glyphs/*.gabc
```
(this last one assumes the shell will expand the wild card)

**Comment by rpspringuel** [comment]
Huh...  I must have had the syntax wrong on my previous attempts.  It's clearly working now.
