### ISSUE TITLE
Error with cp

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-test#7]
On a Mac the latest tests create the following problem:
```
cp: the -H, -L, and -P options may not be specified with the -r option.
```

My guess is that `cp` as implemented on a Mac is not the same as the GNU version on Linux boxes.  It might be wise to implement a solution for `cp` similar to what is in place for `sed` so that I can redirect the tests to the GNU version (which is `gcp` on my system).

**Comment by henryso** [comment]
I just pushed a new version which allows `cp` to be set via `$CP` and `rm` to be set via `$RM`.  Let me know if that works for you.

**Comment by rpspringuel** [comment]
Works.  Tests are running again just fine.
