### ISSUE TITLE
Minor font differences

### ISSUE THREAD

**Issue by rpspringuel** [gregorio-project/gregorio-test#8]
I accidentally just pushed a commit to master of a couple of minor font differences that are showing up on my machine.  I meant to create a pull request so that others could check first, but pushed to the main repository instead of my fork.  If some one could check and make sure the changes don't break other systems, I'd appreciate it.  If they do create problems for others, I'll revert the changes, but figured that there's no need to create that kind of mess in the history if there are no problems.

**Comment by henryso** [comment]
It does fail on my system, but it really should be tolerant of these things, so don't back this out, and I will see if I can tweak the comparison tolerances.

**Comment by henryso** [comment]
I switched to using a perceptual hash for finding differences. It will work by construction since the files exactly match your version.  However, on my system, these changes pass while things that are more significant still fail, so let give this algorithm a shot. Closing this issue.

**Comment by henryso** [comment]
N.B. e0962c7c81af584b33682620ced3e558af6a3210
